### ISSUE TITLE
Warning: The 'strict-error-throw' rule requires type information.

### ISSUE THREAD

**Issue by Goom11** [aleung/tslint-strict-error-throw#1]
I'd like to thank you for making this!

I noticed this warning coming from TSLint "Warning: The 'strict-error-throw' rule requires type information.". It is not an error and the actual function of this lint rule works great but I just wanted to point out the warning message.

Thanks,
Aman Agarwal

**Comment by Goom11** [comment]
Note: I don't know what this error message means but if I am guided in the right direction I am open to fixing this and submitting a PR.

**Comment by aleung** [comment]
This rule requires type information.

Please check [this](https://stackoverflow.com/questions/46715843/what-is-the-meaning-of-tslint-warning-the-no-use-before-declare-rule-requir) SO question.
